### ISSUE TITLE
`GetConsoleMode` Git-bash  not working

### ISSUE THREAD

**Issue by MOZGIII** [TimonPost/crossterm#125]
I have the following error whn trying to use crossterm-powered app from git bash on Windows 10:

```shell
$ app.exe
Getting mode failed
Error: The handle is invalid. (os error 6)
```

I'm running the app with elevated permissions (as admin).

**Comment by TimonPost** [comment]
Are you running the key_events example? Because I see the error happing there

**Comment by TimonPost** [comment]
The windows console functions only work on windows consoles, Git Bash is MinTTY which is not a Windows console and thus it fails to execute some WinAPI functions.

**Comment by MOZGIII** [comment]
Yes, I think that's the situation: I was running my cli app under git-bash, and it's utilizing MinTTY. The tricky thing it it's not known at compile time inder which console the user will be executing the app, so I'd expect the windows compile target to support CMD, PowerShell and MinTTY, as well as new ConPTY interface. I understand that's not what `crossterm` currently provides.

**Comment by TimonPost** [comment]
Most of the functionalities are working in gitbash tough, only functionalities that are really platform specific like input, cursor position, terminal-resize won't work. Styling, cursor movement and such should still be working because git bash supports ANSI escape code which crossterm tries to use before going over to WinAPI, this check is done at run time.

Currently, crossterm can detect if the console is a console that supports WinAPI, that's why it uses ANSI codes on Windows 10 and git bash.  However, as said above reading input is a platform specific thing, on UNIX libc is used and for Windows, WinAPI is used. There is no such thing as reading input with ANSI codes.

I will see if there are ways to work around this.

**Comment by MOZGIII** [comment]
Cool, thanks!
I really needed just a simple menu, maube there's a way to implement it less playform-dependent way?
My code in particular that's causing the issue is here: https://github.com/MOZGIII/rebootinto/tree/master/tui

**Comment by TimonPost** [comment]
Your link is the root of the project :), where is the issue specifically caused?

**Comment by MOZGIII** [comment]
The relevant codepath is here:
https://github.com/MOZGIII/rebootinto/blob/ceb8e37516dbb54b960508c53bd63ca7cecc9ff1/tui/src/main.rs#L34-L54
`ui.run`:
https://github.com/MOZGIII/rebootinto/blob/ceb8e37516dbb54b960508c53bd63ca7cecc9ff1/tui/src/ui.rs#L32-L82

**Comment by MOZGIII** [comment]
Overall the app is extremely trivial, it initializes it's "core backend" (implements app's "payload", not relevant for the issue) and the it goes directly to the UI rendering. I'm using `tui`, and I have a layer that allows me switch `tui` backend (as well a input abstraction backend) at compile time. I had to experiment with different `tui` backlend to see if other implementation have the same issues. Btw the terminus from the PR with windows support behaves the same way as crossterm, both with git-bash and that other powershell issue that I had. I'm now thinking this may be a `tui` issue.

**Comment by TimonPost** [comment]
Closing in favor of https://github.com/TimonPost/crossterm/issues/168
