### ISSUE TITLE
Fix crossterm MinTTY, ConPTY comitability issues on Windows

### ISSUE THREAD

**Issue by TimonPost** [TimonPost/crossterm#168]
# Task Description
Functionalities that are really platform-specific like input, cursor position, terminal-resize won't work. Styling, cursor movement and such should still be working because git bash supports ANSI escape code which crossterm tries to use before going over to WinAPI, this check is done at run time.

Currently, crossterm can detect if the console is a console that supports WinAPI, that's why it uses ANSI codes on Windows 10 and git bash. However, as said above reading input is a platform-specific thing, on UNIX libc is used and for Windows, WinAPI is used. There is no such thing as reading input with ANSI codes.

# Task Todo

In  MinTTY, ConPTY terminal on windows, we are not allowed to call into WinAPI, as we do with input or cursor position. Figure out how we can detect that we are on windows and figure out how to perform those actions with WinAPI

**Comment by MOZGIII** [comment]
Microsoft has recently opened their windows terminal infrastructure: https://github.com/microsoft/terminal
This project does not only contain new Terminal app, but full source for old infrastructure too (cme.exe, conhost.exe, etc). Might be useful to just go there and take a look at the code, or create an issue and ask for help.

**Comment by imdaveho** [comment]
I did some investigation here:

To detect if you're running MinTTY:
https://stackoverflow.com/questions/37460073/msys-vs-mingw-internal-environment-variables

This is because the `"TERM"` env variable reports `xterm-256colors` regardless of OS, and Rust doesn't have a built-in way to detect OS's outside of `cfg!`. By looking for `MSYSTEM`, there is an explicit check for that particular implementation which doesn't include `termios.h`. Also, trying to replicate this native function is non-trivial: https://github.com/mintty/mintty/issues/56

The next thing for setting terminal defaults is that getting the Handle to stdout crashes, but getting it for conout doesn't. So by using a combination of the above and detecting that you're on MinTTY, then use conout settings right at the start will allow for things to run smoothly.

Just fiddling around, so didn't make any PRs but willing to update and test more comprehensively. 

I have no idea about ConPTY though.

**Comment by Biswa96** [comment]
Cygwin now has Windows ConPTY support. See [this commit][1]. Released in Cygwin 3.1.0-0.3 test build.

[1]: https://sourceware.org/git/?p=newlib-cygwin.git;a=commit;h=169d65a5774acc76ce3f3feeedcbae7405aa9b57

**Comment by imdaveho** [comment]
@TimonPost I wonder if you can close this. It seems this is more of an issue with the terminal applications themselves vs any library to interface with the underlying system. As both @MOZGIII and @Biswa96 the "fix" is to use an up-to-date program. The windows implementation is focused on `cmd.exe` and `powershell.exe` anyway, so common programs like `git-bash.exe` or `conemu`.

I also realized that my "discovery" about using `CONOUT$` is moot, as it only bypassess the panic for not being able to find `STDOUT$` handle, but the Handle I receive from `CONOUT$` is empty. So for example, even if there isn't a panic, getting cursor position return `(0, 0)` without errors.

Running `winpty` within `git-bash` works. So I believe either that or running an application that implements ConPTY like the new Windows Terminal app @MOZGIII mentioned would be the best work around. 

Further confirmation here: https://devblogs.microsoft.com/commandline/windows-command-line-introducing-the-windows-pseudo-console-conpty/

Where the blog post mentions that for CLI application devs need not worry or do anything different:
![image](https://user-images.githubusercontent.com/13990019/65267898-fa1ac300-dae3-11e9-9a56-f2422b55ab2b.png)

**Comment by TimonPost** [comment]
Right, I see that it looks like we can close this. If needed, we can always re-open it
