### ISSUE TITLE
Add serde support

### ISSUE THREAD

**Issue by zesterer** [TimonPost/crossterm#179]
It would be very useful to be able to serialise things like the colour and attribute types in `crossterm`.

**Comment by TimonPost** [comment]
Good idea, however, it needs to be behind a feature flag.

**Comment by arnej** [comment]
This would be very useful for me. I need KeyEvent to implement Deserialize and Serialize.
Can you tell us why this needs to be behind a feature flag?

I would like to help with this if I can.

**Comment by TimonPost** [comment]
I have two reasons for that:
1) Because I want to have as less external deps as possible. Currently, I only have WinApi and Libc. 
2) Not all users are going to use serde serialize and deserialize and the dependencie to serde is going to be unnecessarily in most cases.

If you have questions on how to implement this please ask away here :)

**Comment by arnej** [comment]
That sounds reasonable :)

I will have a look at this soon and will come back to you when I can't find out how to implement this as a feature.

**Comment by arnej** [comment]
I finally had the time to work on this. See my pull request here: [#190](https://github.com/TimonPost/crossterm/pull/190)

**Comment by TimonPost** [comment]
Thanks!
