### ISSUE TITLE
Screen API thoughts / proposal

### ISSUE THREAD

**Issue by zrzka** [TimonPost/crossterm#241]
## API

For both variants, no `impl ... for Stdout`.

### 1st variant

Not everything must be a structure / enum. Simple functions?

```rust
pub fn enable_raw_mode() -> Result<()>;
pub fn disable_raw_mode() -> Result<()>;
pub fn show_alternate_screen(raw_mode: bool) -> Result<()>;
pub fn hide_alternate_screen() -> Result<()>;
```

### 2nd variant

Or if you'd like to keep similar API as other sub-crates do provide, something like?

```rust
pub struct RawMode {
    pub fn enable() -> Result<()>;
    pub fn disable() -> Result<()>;
}

pub struct AlternateScreen {
    pub fn show(raw_mode: bool) -> Result<()>;
    pub fn hide() -> Result<()>;
}
```

## Motivation

Current:

```rust
{
    // Keep the screen because of the `drop` logic
    let _screen = AlternateScreen::to_alternate(true)?;
    do_something();
    // _screen.drop() -> _screen.to_main()
}
```

New (1st variant):

```rust
show_alternate_screen(true)?;
do_something();
hide_alternate_screen(true)?;
```

New (2nd variant):

```rust
AlternateScreen::show(true)?;
do_something();
AlternateScreen::hide()?;
```

Same applies to the `RawScreen`.

Sitting on the train, thinking about this ...

* What is the reason to force the user to keep `_screen`, `_raw`, ...?
* What is the reason to force the user to think about the _"drop magic"_?

What motivation is behind this design? I mean, it's totally possible that I'm overlooking something. Do we think that they will forget to disable alternate screen / raw mode and thus we're forcing this behaviour in the `impl Drop`?

**Comment by TimonPost** [comment]
So this was on my bucket list as well. I don't like how the user has to keep the variable around.

> What is the reason to force the user to keep _screen, _raw, ...?

This design had to do with the reasons how crossterm worked before 0.6.0. 

The screen was needed to save the state (stdout). With this state the user could write to the alternate screen. This status had to be saved as long as the user wanted to write to the alternate screen. After some time I discovered the fact that this state was not needed anymore. 

What is the reason to force the user to think about the "drop magic"?

2) It is very annoying if you turn on raw mode but forget to turn it off before the end of your program. Because then your whole terminal is messed up. The same is with alternate screen. If you don't turn it off then your terminal will stay in that state. By means of drop I could make sure - to do the user a favor - that alternate/raw modes were always disabled as soon as the application closed.

I have a preference when crossterm cleans itself up and so does not leave any traces behind. You could say that the user would finally be responsible for the things he does himself, what do you think? The settings that crossterm makes are not very harmful, because when the terminal is closed everything is gone, only as long as it remains open you will suffer from settings that crossterm does. 

For the screen struct I had more ideas in mind please have a look at [this issue](https://github.com/TimonPost/crossterm/issues/167). 

So whether we want to go for another design depends on 1) do we want to do what to have multiple screens (see above issue)  2) do we want crossterm to clean itself up

**Comment by zrzka** [comment]
Ah, I missed this issue. I think it has no sense to clean the API just for _cleaning it_ now when there's a plan for multiple screens, etc.

> I have a preference when crossterm cleans itself up and so does not leave any traces behind. You could say that the user would finally be responsible for the things he does himself, what do you think? The settings that crossterm makes are not very harmful, because when the terminal is closed everything is gone, only as long as it remains open you will suffer from settings that crossterm does.

It's not a bad thing to help / do a favour to the user. On the other side, there're questions I'm unable to answer, like - is keeping the `screen`, `raw`, ... value worth it? Can user do something else with the terminal that it will end up _"damaged"_ even if the alternate / raw will be cleaned by us? I don't know.

Just to be clear, I'm not questioning cleanup in the `Drop`. I'm a bit concerned about the need to keep the value around.

Maybe something like ...

```rust
Screen::with_raw_mode(|| {
    // do whatever you want to do
}); // raw mode off
```

... or other patterns.

**Comment by zrzka** [comment]
Closing this in favour of #167. They're interlinked and I'm sure that we wont forget to discuss it.

**Comment by TimonPost** [comment]
I get your concern, I don't like it as well. It is a desingn from how crossterm used to work < 0.6. Since this issue is likely getting fixed with multiple screens. We can think further about it in a later stage.
