### ISSUE TITLE
How to change font size

### ISSUE THREAD

**Issue by longwusha** [TimonPost/crossterm#36]
I want to make the font size smaller, what should I do?

 I didn't find the information in the documentation and examples.

**Comment by TimonPost** [comment]
That is because it is not yet supported unfortunately.

**Comment by TimonPost** [comment]
Some research needed to see if this is possible to implement.

**Comment by longwusha** [comment]
More detail information can be found in this [blog](https://blog.csdn.net/c0c0cf/article/details/7713354).

**Comment by longwusha** [comment]
In a Unix environment, we might find some inspiration from the console-setup tool.

**Comment by TimonPost** [comment]
Nice finding. We only need some code on how to do this in UNIX. 

I am not sure if this is going to work out because every terminal supports different fonts and different options for fonts. So we can make some kind of generic support but this crated is meant to support all platforms and to my knowledge I don't see much things in common if it goes about font.

Maybe we can provide some kind of tools so the user can manually play with the different font options the terminal has he wants to use.

**Comment by longwusha** [comment]
The font types supported by different terminals may be different, but they should all support adjusting the font size. 

The font size setting should be a generic interface, which will give the terminal more possibilities. 

If we can make the font smaller, we can use the terminal to simulate rendering more things, maybe a picture, maybe a video.

**Comment by longwusha** [comment]
One idea is that we provide an interface to help the user detect which fonts are supported by the current terminal, and then the user can select one of these fonts as needed.

**Comment by TimonPost** [comment]
Yea those are great ideas! Think maybe just as you said it providing tools for the user is probably already good enough. 

Currently I am working on some other projects just taking a little brake from this crate since I had been working on it for 8 months :). But I am willing to investigate into these features. See what is possible. And feel free to also look at certain options, and open an PR if you think you have an great idea. Together we certainly can make it work faster.

**Comment by TimonPost** [comment]
Closing in favor of https://github.com/TimonPost/crossterm/issues/166
