### ISSUE TITLE
How to add more tested terminals

### ISSUE THREAD

**Issue by longwusha** [TimonPost/crossterm#37]
My development environment is deepin linux, I want to test and use the crossterm tool in deepin linux.

Is there a basic set of use cases to test crossterm compatibility on a new terminal. Do I need to execute all the test cases in the code?

**Comment by longwusha** [comment]
I have tried using the code to control the size of the terminal window, but I failed, and the window size has not changed since the code was executed.

**Comment by jojolepro** [comment]
cargo run --example examplename

Names of examples are listed in the Cargo.toml file at the base of the repository source tree

**Comment by TimonPost** [comment]
The closed you can come to see if everything is working are the following examples:

https://github.com/TimonPost/crossterm/tree/master/examples/program_examples

You may want to also checkout what @jojolepro said. There are a few examples in the cargo.toml you can run with the cargo command. 

Maybe I know how to solve the terminal resize issue. I also encountered the problem. The thing is that it is working but it resizes the terminal buffer not the terminal window itself. I think this is a problem of the terminal you are using because they are not handing  ansi escape codes the right way. But maybe I know some way around.

What terminal are you using?

**Comment by longwusha** [comment]
Thank you very much for your help, I already understand what I have to do. I will take the time to do some tests outside of work, and then I will tell you the test results.

**Comment by TimonPost** [comment]
closing this issue since it is not really relevant anymore.
